#!/bin/bash
#SBATCH --account=fc_phact2d3D
#SBATCH --partition=savio
#SBATCH --nodes=1
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=1
#SBATCH --time=00:10:00
#SBATCH --job-name=dedalus
#SBATCH --output=dedalus_output_%j
#SBATCH --error=dedalus_error_%j
export SLURM_EXPORT_ENV=ALL
#export I_MPI_FABRICS=shm,tcp
###conda init bash
conda activate dedalus2

SUBMITDIR=$SLURM_SUBMIT_DIR
WORKDIR=./dedalus_$SLURM_JOB_ID
mkdir -p "$WORKDIR" && cp -r inclined_porous_convection.py "$WORKDIR" && cp -r plot_slices.py "$WORKDIR" && cd "$WORKDIR" || exit -1

ln -s /home/cliu124/dedalus_example/inclined_porous_convection_v2/X1_checkpoint_s1.h5 restart.h5
mpiexec -n $SLURM_NTASKS python3 inclined_porous_convection.py
mpiexec -n $SLURM_NTASKS python3 -m dedalus merge_procs analysis
mpiexec -n $SLURM_NTASKS python3 plot_slices.py analysis/*.h5

cd "$SUBMITDIR" && cp dedalus_output_$SLURM_JOB_ID "$WORKDIR"