#!/bin/bash
#SBATCH --account=changliu
#SBATCH --partition=savio
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=12:00:00
#SBATCH --job-name=dedalus
#SBATCH --output=dedalus_output_%j
#SBATCH --error=dedalus_error_%j
export SLURM_EXPORT_ENV=ALL
#export I_MPI_FABRICS=shm,tcp

conda activate dedalus2

mpiexec -n $SLURM_NTASKS python3 stochastic_forcing_2D_v2.py

